[build]
  command = "node netlify-build.js && vite build"
  publish = "dist/public"

# Handle SPA routing for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTPS
[https]
  force = true